#!/bin/bash
# to be used in the server

# Get the image name from the first argument
image_name=qweryuio423/music-bot:latest

container_name=music_bot

# Pull the latest version of the image
sudo docker pull $image_name

# Stop all instances of the old image
sudo docker stop "${container_name}"
# sudo docker stop "${container_name}2"

sudo docker rm "${container_name}"
# sudo docker rm "${container_name}2"

# Run the latest version of the image
sudo docker run --env-file music1.env --name "${container_name}" $image_name
# sudo docker run --env-file music2.env --name "${container_name}2" $image_name